{% set name = "raven-aiohttp" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raven-aiohttp-{{ version }}.zip
  sha256: 1444a49c93a85b8bb57c6ee649e512368dce7a26ad64ac3a01d86aa5669d77f3

build:
  number: 1003
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - aiohttp >=2.0
    - python >=3.6
    - raven >=5.4.0

test:
  imports:
    - raven_aiohttp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/getsentry/raven-aiohttp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'An aiohttp transport for raven-python'

extra:
  recipe-maintainers:
    - mcs07
