appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jF+S9oztA5j2fiXOYX4op81ohktkhMRsFFiB54ekOjH2gQSzE0FtHJkMUjcH/uJHgX4RKnQWTgo1DBiRYlOFrH1f4CIXOJdFJld+QPdVEIl+x2d0L2EY6ArFTILuHipykqCyLXBabZp2kU1B0RYmewkFtRFimyW3XHpobnocF2qJYd5CGFj1zLUAtZ8Z0321OpeosESz1lT6b3U88R1Dnw11bYsVhRIJ+bECsxo7JXMmy8O4wQCYj37M5p/DFRiIpsVsTYi6gjkEbPgsY700K7AGvgk8XCIVVuJ4872Z5262ICCmGGmbPjgqdkfZV6e8PYz3CExJ3Ktmzw5xoGpQnGNdya8tx4fXyb1IqQY3aeJTGIhBGDchgfBGWtElrbC+rhVIi80G4ZWpzMPQHLOSNO6phtD47dtph7z+vFK57yvf7H5iG9kwpTeY2rARZztzSdNBlKx4yzWuZybxDea4ccvht5sgEnDYiMlLU6j7vKGgGLKkRN/qMF1jPPG1yShtB2MejNdqmWksrnhHxrDUJ4RGEpjkhmJ8vnzW7kRFwfHss7GINzSiSLMOYyOPLyKHHX21l3VJ4dXAwH5G77YR2Ndn9CjItl878+Pp6/LrNfSVTKHI0/WT2VYikMjXTQ88PxqBSzH5mUFnDmLfgnvX/ETppuh7I6pV3UZTt6CjuHo=}
conda_forge_output_validation: false
