travis:
  secure:
    BINSTAR_TOKEN: PPMws3aAmlyujS6x+oyOatVJmteL19yt/xjo5mWPbo4pAEn1AOFkE8Y5n1bDWbJy1IOyibbjzDQBcCz1InkQBLTeN9P0BssI/bQwH4bGGtDEH7wC5nRljzMqWLU691w7o8U4FV/ho/UUYTWklmr2dzpDXTHX9cwuelX7xq3d4myphWtjLsL5BB6IIZI1wbAwlRCYBTkKl6zt4WnQ4HL3bXzsxgpXK4KnuGMFIKkJAQF4eHXv6bx1q0ybjsF+stAX0LQG3WijLcVLymf8TGNDKQBzGETw4Yyx6ysyhNBj3ZDdHPFfrU7NWvkDwJxPzRR9CopfYleC13qvenlP0+hSUXRkIvsC8MGhIovZgU6p2gUYITyMLF5JLse5wh+IWP1aLaH1xUxFiBv56ArcePQ0uAdBbKSTVCkXFmisoj1IlQtE4QRrdoqN2cU5sGSC8Q1G4jTdsKk+Gj4xgHBBKgraE0oxFLapjDmT77uVxwLMiJdyhQtcuu7PWEAaESKRR8S1PWHPzwze48YVXxYQ7fEMk7a0kJRvlUwQr6Mrfdepo1eepszCMdcQRVf43GIHk3OOPGlurlzBguj6o6fKRImOXUFjbnSu+QHm/8Zfha1bM5ldkjE8ht3KSMivN+Oo51BltTgNtnso3wbWjAv96sVdH92wkxM/NythJjtuWE1SH9M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
